server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/greenlearner01/cloud-config-props


        health:
          enabled: true
      name: config-server

management:
  endpoint:
    health:
      show-details: always

